apiVersion: apps/v1
kind: Deployment
metadata:
  name: redhat-pine-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redhat-pine-app
  template:
    metadata:
      labels:
        app: redhat-pine-app
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/gitops-lab/gitops-demo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redhat-pine-app
spec:
  selector:
    app: redhat-pine-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
